name: Node.js Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  CI/CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: build
        run: npm ci
      - name: Jest Tests
        run: npm test
      - name: eslint
        run: npm run lint
